### ISSUE TITLE
项目投稿

### ISSUE THREAD

**Issue by barryzpc** [88250/awesome-seeds#10]
仓库 URL：https://github.com/hyperf/hyperf
项目描述：Hyperf 是基于 Swoole 4.4+ 实现的高性能、高灵活性的 PHP 协程框架，内置协程服务器及大量常用的组件，性能较传统基于 PHP-FPM 的框架有质的提升，提供超高性能的同时，也保持着极其灵活的可扩展性，标准组件均基于 PSR 标准 实现，基于强大的依赖注入设计，保证了绝大部分组件或类都是 可替换 与 可复用 的。

**Comment by 88250** [comment]
你好，仅接受 500 星以下的小型开源项目，欢迎来投稿新作品 😄
