### ISSUE TITLE
项目投稿 Ayer

### ISSUE THREAD

**Issue by shen-yu** [88250/awesome-seeds#21]
仓库 URL：https://github.com/Shen-Yu/hexo-theme-ayer

> 一款安静且优雅的Hexo主题，快速且响应式。

**Comment by 88250** [comment]
感谢投稿，但该项目已经超过 500 星了，投稿指南请参考[这里](https://github.com/88250/awesome-seeds/blob/master/.github/CONTRIBUTING.md)。
